### ISSUE TITLE
Could not connect to socket

### ISSUE THREAD

**Issue by richardcw1** [dspinellis/lego-power-scratch#1]
I found that I got an error when testing the module with, "irsend SEND_ONCE LEGO_Single_Output 1B_5": I received the following response...
   irsend: could not connect to socket
   irsend: No such file or directory

But I managed to overcome this by uncommenting the following line in /boot/config.txt
   dtoverlay=lirc-rpi

Best regards
Richard :^)

**Comment by dspinellis** [comment]
Thank you! I added this in the README file.
