### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by richardcw1** [dspinellis/lego-power-scratch#2]
There seems to be something wrong with the configuration using Single_Output:

curl https://raw.githubusercontent.com/dspinellis/lego-lirc/master/Single_Output">PWM command file |
sudo dd of=/etc/lirc/lircd.conf/Single_Output

Please can you clarify the file extension (?.conf)
Also should the file be put in the /etc/lirc folder, or should it replace lircd.conf?
Also should this be set up in hardware.conf, or not?

Sorry perhaps this is obvious with a little knowledge of Linux, but I don't have that (yet!)

**Comment by richardcw1** [comment]
I get no error messages when I save the file as lircd.conf, but I also get apparently no output from GPIO22. I am wondering whether it is software issue? http://t.co/t50MCZ9De8

**Comment by dspinellis** [comment]
There was a typo in the configuration instructions, which were also a bit too abstract.  I've corrected both issues.  Please follow the revised instructions, and open another issue if you see another problem.  It seems you're debugging the process; apologies.

**Comment by dspinellis** [comment]
Instructions revised again, sorry.

**Comment by richardcw1** [comment]
Thank you for the update. Don't worry about it as I'm enjoying learning more through trying to solve the problems myself!
Your latest update works well for me in that it has now created one lircd.conf file that is comprised of the three LEGO conf modules concatenated, but I had to execute "sudo service lirc restart" otherwise I received the same "irsend: could not connect to socket / irsend: No such file or directory" errors as before.
Now I'm working on my hardware integration! I have a nice break-out board from vilros.com and connected a simple LED-resistor network to pin 22, in order to show the output working at least with a simple low-power red LED and 1K0 resistor. Unfortunately I get no output at all. I'm wondering if there is a problem with my PI output, or whether there is something still not quite right in the SW. Is there a way to debug the SW by sending output to screen when it actually runs the correct code?
Meanwhile I'm going to switch the gpio_out_pin in /etc/modules from 22 to 5, because currently 5 seems to be definitely working although unconfigured, as it drives the red LED at half brightness.

**Comment by dspinellis** [comment]
Switching the I/O pin is, of course, fine.  Note that you can "view" the light of infrared LEDs through a digital camera's screen.

**Comment by richardcw1** [comment]
Hmm... reading the lirc manual it seems that concatenation of the three
configuration files is not good any more...
A8 : Using multiple remotes

lirc will happily accept several lircd.conf file. When doing so, it will
try to match input with each configuration until there is a match. This
means that the number of configurations has some limits, otherwise it would
take too long time. For practical scenarios say 2-4 remotes this shouldn't
really be a problem on modern hardware. There are a number of ways to
combine several configurations:
The old method has been to just paste several configuration files into
lircd.conf. This method is deprecated, since you will loose track of which
files that actually are in use.

Source:
http://www.lirc.org/html/configuration-guide.html#key-symbols-using-lirc-drivers

**Comment by dspinellis** [comment]
In our case the configuration files are for a single remote, so it shouldn't be a problem.  However, preserving the original files is good, so the use of `/etc/lirc/lircd.conf.d/` is appealing.  I will modify the instructions at some point.

Note that I think I've sussed out your problem.  See the updated README file if you still haven't made the remote work.
