### ISSUE TITLE
Unable to run control.py script

### ISSUE THREAD

**Issue by richardcw1** [dspinellis/lego-power-scratch#4]
I'm delighted to write that the irsend command is now working beautifully. Thanks for the updates related to the new kernel.
I was not able to start the control.py script. I then searched and could not find it on the system; should I copy it from somewhere?

**Comment by dspinellis** [comment]
Download it from this repository or clone the repository.

**Comment by richardcw1** [comment]
Ah I see. Sorry I thought this repro was Phillip Quiza's one referred to above. Obvious now you've pointed it out.
It now works a treat with scratch. Mission accomplished! Thank you for posting this really interesting functionality and for your help. Richard :^)
